# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk:
  - oraclejdk8
services:
  - mysql
  - postgresql
  - docker

cache:
directories:
- '$HOME/.m2/repository'

before_script:
  - mysql -e 'create database travis;'
  - psql -c 'create database travis;' -U postgres

install: /bin/true
